export {};

// Custom secrets/vars, set via `wrangler secret put <NAME>` in production and
// via `.dev.vars` locally. Not generated by `wrangler types` (which only
// knows about bindings declared in wrangler.jsonc), so declared separately
// here and merged into the ambient `Env` interface from worker-configuration.d.ts.
declare global {
  interface Env {
    SESSION_SECRET: string;
    ALLOWED_EMAILS: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    ANTHROPIC_API_KEY: string;
    GROQ_API_KEY: string;
  }
}
